prometheus_version: "2.51.0"
prometheus_web_listen_address: "0.0.0.0:9090"

prometheus_global_config:
  scrape_interval: 15s
  evaluation_interval: 15s

prometheus_scrape_configs:
  - job_name: "node_exporters"
    static_configs:
      - targets:
          - "x.x.x.x:9100"
        labels:
          alias: "name"
      - targets:
          - "x.x.x.x:9100"
        labels:
          alias: "name"
      - targets:
          - "x.x.x.x:9100"
        labels:
          alias: "name"

