{
 "title": "System Health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (alias) (\n  rate(node_disk_read_bytes_total{job=\"node_exporters\", device!~\"^loop.*|^ram.*\"}[1m])\n)",
     "legendFormat": "{{alias}} - {{device}} Read"
    },
    {
     "expr": "sum by (alias) (\n  rate(node_disk_written_bytes_total{job=\"node_exporters\", device!~\"^loop.*|^ram.*\"}[1m])\n)",
     "legendFormat": "{{alias}} Write"
    }
   ]
  },
  {
   "title": "Network Traffic In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (alias) (\n  rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])\n)\n",
     "legendFormat": "{{alias}} In"
    },
    {
     "expr": "sum by (alias) (\n  rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])\n)",
     "legendFormat": "{{alias}} Out"
    }
   ]
  },
  {
   "title": "Disk Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}) \n/ node_filesystem_size_bytes{mountpoint=\"/\"}\n",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (\n  node_memory_MemAvailable_bytes{job=\"node_exporters\"}\n  /\n  node_memory_MemTotal_bytes{job=\"node_exporters\"}\n))\n",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "CPU Usage  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (avg by (alias) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n) * 100)\n",
     "legendFormat": "{{alias}"
    }
   ]
  }
 ]
}